// Generated by Wrangler on Mon Sep 16 2024 18:25:55 GMT+0900 (Korean Standard Time)
// by running `wrangler types --env-interface=CloudflareEnv`

interface CloudflareEnv {
	BUN_VERSION: "1.1.27";
	DISCORD_BOT_TOKEN: string;
	DB: D1Database;
}
