name = "rss-watch"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BUN_VERSION = "1.1.34"
NODE_VERSION = "22"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "rss.watch"
database_id = "28b59e64-a09a-44e9-8598-6d9225a2a6a1"

[placement]
mode = "smart"
