name = "rss-watch"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BUN_VERSION = "1.1.34"
NODE_VERSION = "22"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "rss-watch-prod"
database_id = "407180e4-9256-4d3d-b1aa-4160461e9675"

[placement]
mode = "smart"
