name = "rss-watch"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BUN_VERSION = "1.1.34"
NODE_VERSION = "22"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "rss-watch"
database_id = "50baee97-6dd2-4ef5-a072-012a50965081"

[placement]
mode = "smart"
